### ISSUE TITLE
Creation failed in PG11

### ISSUE THREAD

**Issue by GHNewbiee** [petere/pguint#12]
Hi, I have tried to install the extension in `PG11` but I got plenty warnings and notes:
`implicit declaration of function ‘GET_1_BYTE’ [-Wimplicit-function-declaration]`
or
`implicit declaration of function 'GET_1_BYTE' is invalid in C99 [-Wimplicit-function-declaration]`

After "successful" compilation, linking, and installation the extension was **not** created, displaying the following error:
`SQL Error [XX000]: ERROR: could not load library "/usr/lib/postgresql/11/lib/uint.so": /usr/lib/postgresql/11/lib/uint.so: undefined symbol: GET_1_BYTE`

I tried to change the code in `unit.h` but I failed to make it run. With my little knowledge and recent "bad" experience I suspect it may not be only a matter of correct declaration but maybe beyond that.

Tia

PS: In PG10, the extension was created without any problem.

**Comment by gsalzer** [comment]
The definition of `GET_1_BYTE` used to be in `postgres.h`, a header file of the Postgres distribution, but in version 11 it no longer is; in fact, the symbol `GET_1_BYTE` is defined in none of the header files. I don't think that there is an easy fix, short of adapting the code of the extension.

**Comment by GHNewbiee** [comment]
So, does this mean the extension goes to the deep well where there is not return?!!

**Comment by gsalzer** [comment]
I'm not the maintainer of the package, just a potential user who tried to install it (and who had a look at the code). Given that PG11 is out only since a short time, it is probably too early to judge whether the extension is still maintained.

**Comment by mgoldshteyn** [comment]
The fix for this is very easy, define in uint.h DatumGetInt8 as follows:

#define DatumGetInt8(X) ((int8) (X))
