### ISSUE TITLE
Has anyone figured out how to add this extension to a schema?

### ISSUE THREAD

**Issue by SteelBlueVision** [petere/pguint#14]
For example, if I do something like (in a database we will call mydb):

```
CREATE SCHEMA x;
CREATE EXTENSION uint WITH SCHEMA x;

SELECT (5::x.uint4=5::x.uint4);
ERROR:  operator is not unique: x.uint4 = x.uint4
LINE 1: select (5::x.uint4=5::x.uint4);
                          ^
HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.

```
For some reason, the uint extension being installed in a schema seems to break the included comparison operators.

If I cast the uint4 to say bigint, I can compare once again, showing that it is fine with the x.uint4 type, it just doesn't know how to compare to uint4's using the comparison functions built into the extension:
```
select (5::x.uint4::bigint=5::x.uint4::bigint);
 ?column? 
----------
 t
(1 row)

```
I can bypass this by adding a search path:
```
ALTER DATABASE mydb SET search_path TO x;
-- Might need to reconnect for it to take effect
select (5::uint4=5::uint4);
 ?column? 
----------
 t
(1 row)
```
It can now find the equality operator in the search path (and the uint4 type in the x SCHEMA), but this is a total hack. I would imagine that the uint extension should prequalify comparators automatically with the SCHEMA to which it was installed (i.e., SCHEMA x in my example).

**Comment by petere** [comment]
You need to schema-qualify the operator as well, like this:

```
SELECT (5::x.uint4 OPERATOR(x.=) 5::x.uint4);
```

Obviously, setting the search path is less ugly.
