### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by yhuelf** [petere/pguint#22]
Hi,

On my Debian 11 machine, `make` returns with this error :

```
make: generate.py: No such file or directory
make: *** [Makefile:33: operators.c] Error 127
```
I eventually managed to compile the extension, but I had to copy the file `generate.py` in my postgres install path, and I had to insert the following line at the top of it :

`#!/usr/bin/python`

**Comment by petere** [comment]
I suspect that this is because your PostgreSQL installation was built without Python support. The command line called from `make` should be like

```
python3 generate.py 16
```

but I guess in your case, it just tries to call

```
generate.py 16
```

because no Python binary was configured.
