### ISSUE TITLE
unsigned integer arithmetics

### ISSUE THREAD

**Issue by EliR00t** [petere/pguint#26]
it is supposed to be modulo arithmetics.
i.e. 2-1 = 1 and 1-2 = 255 for uint1 
and  1 - 2 = 65535 for uint2

why it is not  implemented like this but with some condition check and error report? 
For example functions uint8uint8pl or uint8uint8mi break modulo arithmetics.

**Comment by petere** [comment]
What you are describing is the behavior of types in C. But in SQL, overflow and underflow is checked. (For example, `60000::smallint + 10000::smallint` fails in PostgreSQL, but it would work in C.)

If you want different behavior, you can also define your own operators.
