### ISSUE TITLE
After clone and just make it does not build

### ISSUE THREAD

**Issue by ridvankorkmaz** [petere/pguint#27]
$ `make`
clang -Wall .................................................................   -c -o misc.o misc.c
generate.py 16
make: generate.py: No such file or directory
make: *** [operators.c] Error 1

I managed to build by running `python3 generate.py 16` before `make`

So, if I do not do anything wrong, `README` should instruct to do so, before `make`.

**Comment by petere** [comment]
This usually happens if the PostgreSQL installation you are building against did not detect a Python program. You could also do something like

```
make PYTHON=python3
```

**Comment by ridvankorkmaz** [comment]
We can close, thanks.
