### ISSUE TITLE
Problem Installation (Windows 10 x64)

### ISSUE THREAD

**Issue by mmmDanone** [petere/pguint#4]
> make

> process_begin: CreateProcess((null), pg_config --version, ...) failed.
> process_begin: CreateProcess((null), pg_config --includedir-server, ...) failed.
> "grep" is not internal or external
> command, executable program or batch file.
> process_begin: CreateProcess((null), pg_config --pgxs, ...) failed.
> makefile:29: no file name for `include'
> cat uint.sql hash.sql hex.sql operators.sql | sed 's/@UINT8_PASSEDBYVALUE@//' >uint--0.sql
> "cat" is not internal or external
> command, executable program or batch file.
> make: *** [uint--0.sql] Error 255

> make install

> process_begin: CreateProcess((null), pg_config --version, ...) failed.
> process_begin: CreateProcess((null), pg_config --includedir-server, ...) failed.
> "grep" is not internal or external
> command, executable program or batch file.
> process_begin: CreateProcess((null), pg_config --pgxs, ...) failed.
> makefile:29: no file name for `include'
> make: *** No rule to make target `install'.  Stop.

**Comment by petere** [comment]
Windows is not supported.
