### ISSUE TITLE
Problem Installation (Windows 10 x64) (sorry, new problem)

### ISSUE THREAD

**Issue by mmmDanone** [petere/pguint#5]
`make`

> grep: 1': No such file or directory
> grep: C:/OSPanel/modules/database/PostgreSQL-10.1-x64/include/server/pg_config.h: No such file or directory
> makefile:29: C:/OSPanel/modules/database/PostgreSQL-10.1-x64/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
> make: *** No rule to make target `C:/OSPanel/modules/database/PostgreSQL-10.1-x64/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

`make install`

> grep: 1': No such file or directory
> grep: C:/OSPanel/modules/database/PostgreSQL-10.1-x64/include/server/pg_config.h: No such file or directory
> makefile:29: C:/OSPanel/modules/database/PostgreSQL-10.1-x64/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
> make: *** No rule to make target `C:/OSPanel/modules/database/PostgreSQL-10.1-x64/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

**Comment by petere** [comment]
Windows is not supported.
